### ISSUE TITLE
期間中のGP30の合計値も表示させてみるのはどうでしょうか?

### ISSUE THREAD

**Issue by yunix-kyopro** [terry-u16/ahc-season-rankings#5]
<img width="855" alt="スクリーンショット 2024-05-29 23 16 00" src="https://github.com/terry-u16/ahc-season-ranking/assets/92100842/83295baa-f923-42b7-86f9-65678326fe3b">
こんな感じのイメージです。他の方も集計していたような気がするのですが、そろそろGP30のスコアで盛り上がりそうな時期になってきたので、表示できたら嬉しいのかなと思いました。
期間が1年を外れると意味のない集計になりますが(複数年のGP30スコアの合計値になる)、まあそれは仕方がないかなという気持ちでいます。
どうでしょうか?

**Comment by yunix-kyopro** [comment]
<img width="687" alt="スクリーンショット 2024-05-30 0 02 00" src="https://github.com/terry-u16/ahc-season-ranking/assets/92100842/a7365ab6-57e6-4d70-b49c-7ae5f77fdb97">

手元で機能を追加しました。もし差し支えなければPRを作ろうと思うのですがどうでしょうか?

**Comment by terry-u16** [comment]
確かに嬉しい気がします！PR作成頂けると嬉しいです……！

**Comment by terry-u16** [comment]
#6 でご対応頂いたのでクローズしますー
